[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

# Configurações de teste
gas_reports = ["*"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }